# Generated by Django 3.1.7 on 2021-04-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_name', models.CharField(max_length=20)),
                ('created_at', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=100)),
                ('score', models.IntegerField(max_length=2)),
                ('sentiment', models.IntegerField(max_length=2)),
                ('subjectivity', models.IntegerField(max_length=2)),
            ],
        ),
    ]
